package cc.stkmn.shareparser.ui

import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.Text as MaterialText
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import cc.stkmn.shareparser.AppLocale
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit

private val exactEnglish = mapOf(
    "Profile" to "Profiles",
    "Importieren" to "Import",
    "Einstellungen" to "Settings",
    "Noch kein Profil" to "No profile yet",
    "Profil erstellen" to "Create profile",
    "Bearbeiten" to "Edit",
    "Löschen" to "Delete",
    "Abbrechen" to "Cancel",
    "Profil löschen?" to "Delete profile?",
    "Geteilte Informationen" to "Shared information",
    "Betreff" to "Subject",
    "Text" to "Text",
    "Kein Profil passt" to "No profile matches",
    "Profil aus diesem Text erstellen" to "Create profile from this text",
    "Passendes Profil auswählen" to "Select matching profile",
    "Profil" to "Profile",
    "Wechseln" to "Change",
    "Erkannte Variablen" to "Detected variables",
    "Weiterverarbeitung" to "Processing",
    "Dieses Profil hat noch keine Aktion." to "This profile has no action yet.",
    "Aktion auswählen" to "Select action",
    "Profil bearbeiten" to "Edit profile",
    "Wie weiterverarbeiten?" to "How should this be processed?",
    "Datum und Uhrzeit" to "Date and time",
    "Deutsch (Deutschland)" to "German (Germany)",
    "Geräteeinstellung" to "Device setting",
    "Darstellung" to "Appearance",
    "Sprache / Language" to "Language",
    "Systemstandard / System default" to "System default",
    "Deutsch" to "German",
    "English" to "English",
    "Aktion" to "Action",
    "Kalendereintrag" to "Calendar event",
    "URL öffnen" to "Open URL",
    "Text oder Textdatei" to "Text or text file",
    "Webhook" to "Webhook",
    "Kalenderfelder" to "Calendar fields",
    "Titel" to "Title",
    "Beschreibung" to "Description",
    "Ort" to "Location",
    "Beginn oder Zeitraum" to "Start or time range",
    "Ende, optional" to "End, optional",
    "Dauer, optional" to "Duration, optional",
    "Ganztägig" to "All day",
    "Zielkalender-Verhalten" to "Target calendar behavior",
    "Kalender-App vorausfüllen" to "Prefill calendar app",
    "Zielkalender verbindlich" to "Use target calendar directly",
    "Standard-Browser" to "Default browser",
    "Als Textdatei ausgeben" to "Output as text file",
    "Dateiname" to "File name",
    "Unterordner, optional" to "Subfolder, optional",
    "Leere oder ungültige Dateifelder" to "Empty or invalid file fields",
    "Fallback verwenden" to "Use fallback",
    "Fehler melden und Aktion abbrechen" to "Report error and stop action",
    "Fallback-Dateiname" to "Fallback file name",
    "Fallback-Unterordner, optional" to "Fallback subfolder, optional",
    "Datei verwenden" to "Use file",
    "Teilen" to "Share",
    "Direkt öffnen" to "Open directly",
    "Im Dateisystem speichern" to "Save to file system",
    "Ausführung" to "Execution",
    "Nur bei Auswahl dieser Aktion" to "Only when this action is selected",
    "Immer senden" to "Always send",
    "Leerer POST-Inhalt" to "Empty POST body",
    "Fehler melden" to "Report error",
    "Fallback-Inhalt" to "Fallback body",
    "Variablen als Profilmerkmal" to "Variables as profile criteria",
    "Nicht leer" to "Not empty",
    "5 Ziffern" to "5 digits",
    "Aktive Merkmale" to "Active criteria",
    "Fester Text als Merkmal" to "Fixed text as criterion",
    "Hinzufügen" to "Add",
    "Variablen aus dem Beispiel" to "Variables from the example",
    "Variable" to "Variable",
    "Variablen" to "Variables",
    "Manuell" to "Manual",
    "Erweiterter Modus" to "Advanced mode",
    "Profil-JSON" to "Profile JSON",
    "JSON anwenden" to "Apply JSON",
    "Profil speichern" to "Save profile",
    "Bearbeitungsmodus aktiv" to "Editing mode active",
    "Fehlerstelle hervorgehoben" to "Error location highlighted",
    "Profilname" to "Profile name",
    "Profil aktiv" to "Profile enabled",
    "Profil deaktiviert" to "Profile disabled",
    "Parsing-Reihenfolge" to "Parsing order",
    "Von oben nach unten" to "Top to bottom",
    "Von unten nach oben" to "Bottom to top",
    "Profil automatisch erkennen" to "Automatically detect profile",
    "Als Variable" to "Use as variable",
    "Als Profilmerkmal" to "Use as profile criterion",
    "Text kopieren" to "Copy text",
    "Textfeld maximieren" to "Maximize text field",
    "Textfeld verkleinern" to "Minimize text field",
    "Beispielwert kopieren" to "Copy example value",
    "Aktion entfernen" to "Remove action",
    "Anzeigename" to "Display name",
    "Icon auswählen" to "Select icon",
    "Inhaltstyp" to "Content type",
    "Quelle" to "Source",
    "Pflichtfeld" to "Required field",
    "Aufteilen" to "Split",
    "Leerzeichen entfernen" to "Trim whitespace",
    "Textteil ersetzen / entfernen" to "Replace / remove text",
    "Text davor" to "Prefix text",
    "Text danach" to "Suffix text",
    "Kleinschreibung" to "Lowercase",
    "Großschreibung" to "Uppercase",
    "Nachricht" to "Message",
    "Nachrichtentext" to "Message text",
    "Dateiinhalt" to "File content",
    "Gesamte Nachricht / Dateiinhalt" to "Entire message / file content",
    "Betreff + Nachricht" to "Subject + message",
    "Teilende App" to "Sharing app",
    "Paketname der teilenden App" to "Sharing app package",
    "Inhaltstyp" to "Content type",
    "Kein Fehlerbericht vorhanden." to "No error report available.",
    "Betroffener Bereich" to "Affected area",
    "Technische Details" to "Technical details",
    "Eingabe" to "Input",
    "Profil an Fehlerstelle bearbeiten" to "Edit profile at error location",
    "Geteilter Inhalt" to "Shared content",
    "Fehlerbericht" to "Error report",
    "Bestimme, wie geteilte Texte erkannt und weiterverarbeitet werden." to "Define how shared text is detected and processed.",
    "Erstelle ein Profil direkt hier oder teile eine Beispiel-Mail mit ShareParser. Aus dem Beispiel kannst du Felder ohne Regex auswählen." to "Create a profile here or share an example email with ShareParser. You can select fields from the example without writing regex.",
    "Diese Einstellung steuert, wie freie Datums- und Zeitangaben für Kalenderaktionen interpretiert werden." to "This setting controls how free-form date and time values are interpreted for calendar actions.",
    "Empfohlen für deutsche E-Mails und Nachrichten." to "Recommended for German emails and messages.",
    "Geräteeinstellung" to "Device setting",
    "Verwendet die Gerätesprache für Textvergleiche. Die flexiblen deutschen Zahlenformate bleiben weiterhin verfügbar." to "Uses the device language for text comparisons. Flexible German numeric formats remain available.",
    "Erstelle aus diesem Beispiel ein Profil. Du kannst anschließend einzelne Zeilen als Variablen markieren, ShareParser erzeugt die Regeln automatisch." to "Create a profile from this example. You can then mark individual lines as variables and ShareParser will create the rules automatically.",
    "Extraktion nicht vollständig" to "Extraction incomplete",
    "Beim ersten Start folgt ShareParser der Systemsprache. Diese Auswahl kann jederzeit geändert werden." to "On first launch ShareParser follows the system language. You can change it here at any time.",
    "Verwendet die Sprache des Geräts." to "Uses the device language.",
    "Deutsch als App-Sprache verwenden." to "Use German as the app language.",
    "Logo 1 ist der Standard und wird auch im Android-Teilen-Dialog verwendet. Beim Wechsel kann der Launcher einige Sekunden brauchen, bis das neue Symbol sichtbar ist." to "Logo 1 is the default and is also used in Android sharing. After changing it, the launcher may need a few seconds to show the new icon.",
    "Format und Erkennung" to "Format and detection",
    "Regionale Schreibweisen und 12/24-Stunden-Format" to "Regional formats and 12/24-hour time",
    "Textdateien" to "Text files",
    "Voreingestellter Speicherordner" to "Default save folder",
    "Nicht gesetzt. Bei einer Datei-Aktion mit „Speichern“ zeigt Android den Dateidialog an." to "Not set. For a file action using Save, Android will show the file picker.",
    "Ordner auswählen" to "Select folder",
    "Ordner ändern" to "Change folder",
    "Voreinstellung entfernen" to "Remove default",
    "Auswahl beim Teilen" to "Share action selection",
    "Wenn genau ein Profil mit genau einer Aktion passt, führt ShareParser sie direkt aus. Diese Einstellung gilt nur, wenn mehrere Möglichkeiten zur Auswahl stehen." to "If exactly one profile with one selectable action matches, ShareParser runs it directly. This setting only applies when multiple choices are available.",
    "Overlay über der teilenden App" to "Overlay above the sharing app",
    "Overlay-Berechtigung erteilt. Die Auswahl erscheint mittig und schließt sich spätestens nach einer Minute." to "Overlay permission granted. The selector appears centered and closes after at most one minute.",
    "Benötigt die optionale Android-Berechtigung „Über anderen Apps anzeigen“." to "Requires the optional Android permission to display over other apps.",
    "Als Benachrichtigung auswählen" to "Select via notification",
    "Eigener Android-Kanal. Ton, Vibration oder stumm stellst du in den Systemeinstellungen ein. Die Nachricht verschwindet spätestens nach einer Minute." to "Uses a dedicated Android channel. Configure sound, vibration or silent mode in system settings. The notification disappears after at most one minute.",
    "Benachrichtigungskanal konfigurieren" to "Configure notification channel",
    "Ausgewählter Ordner" to "Selected folder",
    "Regionale Datums- und Zeitformate" to "Regional date and time formats",
    "Standard ist die Android-Geräteeinstellung. Die Auswahl legt fest, wie mehrdeutige Datums- und Zeitangaben interpretiert werden." to "The Android device setting is the default. This selection determines how ambiguous date and time values are interpreted.",
    "Geräteeinstellung, Standard" to "Device setting, default",
    "Leitet Datumsreihenfolge und 12/24-Stunden-Präferenz aus Sprache und Region des Geräts ab." to "Derives date order and 12/24-hour preference from the device language and region.",
    "abhängig von den Android-Regionseinstellungen" to "depends on Android regional settings",
    "Deutsch, Deutschland" to "German, Germany",
    "Tag vor Monat, 24-Stunden-Zeit sowie deutsche Begriffe wie heute, morgen und Montag." to "Day before month, 24-hour time, and German terms such as today, tomorrow and Monday.",
    "Monat vor Tag. AM/PM wird unterstützt und bei US-Texten erwartet." to "Month before day. AM/PM is supported and expected for US text.",
    "Bevorzugt eindeutige Jahr-Monat-Tag-Angaben und 24-Stunden-Zeit." to "Prefers unambiguous year-month-day dates and 24-hour time.",
    "Bitte einen Profilnamen eingeben." to "Enter a profile name.",
    "Jede Variable braucht einen Namen." to "Every variable needs a name.",
    "Ein Variablenname ist bereits für eine eingebaute Variable reserviert." to "A variable name is reserved for a built-in variable.",
    "Jeder Variablenname darf nur einmal vorkommen." to "Each variable name may only be used once.",
    "Mindestens eine Weiterverarbeitung hinzufügen." to "Add at least one processing action.",
    "Neue Nachrichten oder Textdateien, die du jetzt an ShareParser teilst, werden direkt als Beispiel in dieses Profil geladen." to "New messages or text files shared with ShareParser now are loaded directly into this profile as an example.",
    "Nimmt bei mehrfach vorkommenden Feldern den letzten Treffer. Sinnvoll, wenn die ursprüngliche Mail unter einer Antwort oder Weiterleitung steht." to "Uses the last match when a field occurs multiple times. Useful when the original email is below a reply or forward.",
    "Nimmt bei mehrfach vorkommenden Feldern den ersten Treffer." to "Uses the first match when a field occurs multiple times.",
    "Wähle feste Textteile, die teilende App oder erkannte Variablen als Merkmale. Alle gewählten Merkmale müssen passen." to "Choose fixed text, the sharing app, or detected variables as criteria. All selected criteria must match.",
    "Kombiniere feste Textteile, teilende App und Variablen. Ab dem zweiten Merkmal kannst du UND oder ODER wählen." to "Combine fixed text, the sharing app and variables. From the second criterion onward, choose AND or OR.",
    "Noch kein Merkmal. Ohne Merkmale dient dieses Profil nur als Fallback." to "No criterion yet. Without criteria, this profile is only used as a fallback.",
    "Filter werden nach der Variablen-Extraktion geprüft. Beispiele: „Nicht leer“ akzeptiert jeden Inhalt, „5 Ziffern“ eignet sich z. B. für eine PLZ. Für andere Formate kannst du im erweiterten Modus einen Regex wie ^[A-Z]{2}-\\d{6}$ verwenden." to "Filters are checked after variable extraction. Not empty accepts any content, while 5 digits is useful for values such as postal codes. For other formats, use a regex such as ^[A-Z]{2}-\\d{6}$ in advanced mode.",
    "Markiere einen veränderlichen Wert oben und tippe auf „Als Variable“. Bereits definierte Variablen werden im Beispiel farbig markiert. Beispielwerte lassen sich kopieren und anschließend in Umwandlungen verwenden." to "Select a changing value above and tap Use as variable. Existing variables are highlighted in the example. Example values can be copied and used in transformations.",
    "Zeigt Regex-Details und erlaubt direkte Bearbeitung des Profil-JSON." to "Shows regex details and allows direct editing of the profile JSON.",
    "Gib der Information einen Namen. Das Feld darf beim Bearbeiten vollständig geleert werden." to "Give the information a name. The field may be cleared completely while editing.",
    "Variable erstellen" to "Create variable",
    "Ein leeres Trennzeichen oder ein Leerzeichen teilt nach dem ersten Wort. Für andere Werte kannst du z. B. „,“, „-“ oder „/“ verwenden." to "An empty separator or a space splits after the first word. For other values you can use characters such as ',', '-' or '/'.",
    "Erste neue Variable" to "First new variable",
    "Zweite neue Variable" to "Second new variable",
    "Text gedrückt halten und einen Bereich markieren. Der Text ist kopierbar. Bereits erkannte Variablen sind farbig hinterlegt." to "Press and hold the text to select a range. The text can be copied. Existing variables are highlighted.",
    "Im Beispiel nicht erkannt" to "Not detected in the example",
    "Variablenname" to "Variable name",
    "Umwandlung hinzufügen" to "Add transformation",
    "Textteil entfernen oder ersetzen" to "Remove or replace text",
    "Text davor setzen" to "Add text before",
    "Text danach setzen" to "Add text after",
    "Regex, erweitert" to "Regex, advanced",
    "Entfernt Leerzeichen am Anfang und Ende." to "Removes whitespace at the beginning and end.",
    "Erweiterte Regex-Syntax ist aktiv." to "Advanced regex syntax is enabled.",
    "Ohne Schreibzugriff. Die Kalender-App kann die Zielkalender-Vorgabe ignorieren." to "Without write access, the calendar app may ignore the requested target calendar.",
    "Speichert den Termin direkt im ausgewählten Kalender und öffnet ihn danach zum Bearbeiten. Benötigt Kalender-Schreibzugriff." to "Saves the event directly to the selected calendar and then opens it for editing. Requires calendar write access.",
    "Zielkalender, optional" to "Target calendar, optional",
    "Kalender auswählen" to "Select calendar",
    "Kein fester Zielkalender" to "No fixed target calendar",
    "Im verbindlichen Modus nutzt ShareParser diese lokale Kalender-ID direkt." to "In direct mode, ShareParser uses this local calendar ID directly.",
    "Beim normalen Android-Kalender-Intent ist die Kalender-ID nur eine Empfehlung an die Kalender-App." to "With the normal Android calendar intent, the calendar ID is only a suggestion to the calendar app.",
    "In ShareParser öffnen" to "Open in ShareParser",
    "Erzeugt aus dem transformierten Text eine Datei statt nur normalen Android-Text." to "Creates a file from the transformed text instead of sharing plain Android text.",
    "Öffnet den Android-Teilen-Dialog mit der erzeugten Datei." to "Opens the Android share sheet with the generated file.",
    "Öffnet die Datei in einer passenden App, z. B. Markdown- oder HTML-Viewer." to "Opens the file in a compatible app, such as a Markdown or HTML viewer.",
    "Nutzt den voreingestellten Ordner aus den Einstellungen. Ohne Voreinstellung erscheint der Android-Dateidialog. Der Unterordner kann Variablen enthalten." to "Uses the default folder from settings. Without a default, Android shows the file picker. The subfolder may contain variables.",
    "Der Webhook erscheint wie jede andere Aktion in der Auswahl." to "The webhook appears like any other action in the selector.",
    "Feuert automatisch, sobald dieses Profil zu einem geteilten Inhalt passt." to "Sends automatically as soon as this profile matches shared content.",
    "Fester Text oder Variable" to "Fixed text or variable",
    "Variablen können per Baustein oder direkt als {{name}} geschrieben werden." to "Variables can be inserted with the chips or typed directly as {{name}}.",
    "Kalendertitel" to "Calendar title",
    "Kalender öffnen" to "Open calendar",
    "Link öffnen" to "Open link",
    "Text weiterleiten" to "Forward text",
    "Betreff + Text" to "Subject + text",
    "Nachrichtentext / Dateiinhalt" to "Message text / file content",
    "Ungespeicherte Änderungen" to "Unsaved changes",
    "Möchtest du die Änderungen am Profil anwenden oder verwerfen?" to "Do you want to apply or discard the profile changes?",
    "Anwenden" to "Apply",
    "Verwerfen" to "Discard",
    "Letzte Änderung rückgängig" to "Undo last change",
    "Variablen als Profilmerkmal" to "Variables as profile criteria",
    "Eingeklappt. Wähle bei Bedarf eine oder mehrere Variablen und lege fest, was geprüft werden soll." to "Collapsed. Select one or more variables when needed and define what should be checked.",
    "Variablen auswählen" to "Select variables",
    "Prüfung" to "Check",
    "Ist leer" to "Is empty",
    "Ist nicht leer" to "Is not empty",
    "Inhalt prüfen" to "Check content",
    "Du musst keinen Regex schreiben. Wähle zuerst die Art der Prüfung und gib anschließend nur den Vergleichswert ein." to "You do not need to write regex. First choose the type of check, then enter only the comparison value.",
    "Enthält" to "Contains",
    "Beginnt mit" to "Starts with",
    "Endet mit" to "Ends with",
    "Exakt" to "Exact",
    "Nur Ziffern" to "Digits only",
    "Anzahl Ziffern" to "Digit count",
    "Eigener Regex" to "Custom regex",
    "Anzahl der Ziffern" to "Number of digits",
    "Vergleichswert" to "Comparison value",
    "Prüfung übernehmen" to "Apply check",
    "UND" to "AND",
    "ODER" to "OR",
    "Dateiendung" to "File extension",
    "Unbekannte Endung. Die Datei wird trotzdem als Textdatei mit dieser Endung erzeugt." to "Unknown extension. The file will still be created as a text file with this extension.",
    "ShareParser wählt den passenden Text-Inhaltstyp automatisch." to "ShareParser selects the matching text content type automatically.",
    "Die gewählte Inhaltsprüfung ist noch unvollständig oder der Regex ist ungültig." to "The selected content check is incomplete or the regex is invalid.",
    "JSON übernommen. Speichere das Profil, um die Änderungen anzuwenden." to "JSON loaded. Save the profile to apply the changes.",
    "Profil erkennen" to "Profile recognition",
    "Variablen aus Beispiel" to "Variables from example",
    "Teilende App" to "Sharing app",
    "Optional. Wähle eine installierte App und ob geteilte Inhalte von dieser App stammen sollen oder nicht." to "Optional. Select an installed app and whether shared content should come from this app or not.",
    "Ist" to "Is",
    "Ist nicht" to "Is not",
    "App auswählen" to "Select app",
    "App-Filter entfernen" to "Remove app filter",
    "Variable bereits vorhanden" to "Variable already exists",
    "Überschreiben" to "Overwrite",
    "Mit Nummer speichern" to "Save with number",
    "Lege ein Trennzeichen fest und füge so viele Untervariablen hinzu wie benötigt. Bei leerem Trennzeichen wird nach Leerraum getrennt." to "Choose a separator and add as many subvariables as needed. With an empty separator, whitespace is used.",
    "Leerraum" to "Whitespace",
    "Untervariable hinzufügen" to "Add subvariable",
    "Nach oben" to "Move up",
    "Nach unten" to "Move down",
    "Auswahl-Anzeige" to "Selection display",
    "Im Overlay anzeigen" to "Show in overlay",
    "In Benachrichtigung anzeigen" to "Show in notification",
    "Die Reihenfolge bestimmt auch die Auswahl beim Teilen. Benachrichtigungen zeigen die ersten 3 Aktionen, das Overlay die ersten 4. In der App bleibt die vollständige Liste verfügbar." to "The order also controls share selection. Notifications show the first 3 actions, the overlay the first 4. The full list remains available in the app.",
    "Leer lassen übernimmt die bisherige oder Standard-Endung." to "Leave empty to keep the previous or default extension.",
    "Profil löschen?" to "Delete profile?",
    "Löschen" to "Delete",
    "Änderung rückgängig" to "Undo change",
    "Änderung wiederholen" to "Redo change",
    "Web-Link" to "Web link",
    "E-Mail-Link" to "Email link",
    "Telefon-Link" to "Phone link",
    "Telefonnummer" to "Phone number",
    "E-Mail-Adresse" to "Email address"
)

private fun englishFallback(value: String): String {
    exactEnglish[value]?.let { return it }
    var result = value
    val replacements = listOf(
        "Noch kein Merkmal" to "No criterion yet",
        "Teilende App ist nicht " to "Sharing app is not ",
        "Teilende App ist " to "Sharing app is ",
        "Das Profil '" to "The profile '",
        "' wird dauerhaft gelöscht." to "' will be permanently deleted.",
        "Untervariable " to "Subvariable ",
        "Unbekannte Variable" to "Unknown variable",
        "Erkannte Variablen" to "Detected variables",
        "Variablen können" to "Variables can",
        "Geteilt aus" to "Shared from",
        "Dateityp" to "File type",
        "Datei:" to "File:",
        "Markiert:" to "Selected:",
        "Profil:" to "Profile:",
        "Typ:" to "Type:",
        "Variablen ·" to "variables ·",
        "Aktionen" to "actions",
        "Aktion" to "action",
        "Variable" to "variable",
        "Profilmerkmal" to "profile criterion",
        "Fehler" to "Error",
        "Dateiname" to "File name",
        "Unterordner" to "Subfolder",
        "Kalender" to "Calendar",
        "Speichern" to "Save",
        "Öffnen" to "Open",
        "Teilen" to "Share",
        "Entfernen" to "Remove",
        "Auswählen" to "Select",
        "kopieren" to "copy",
        "optional" to "optional"
    )
    replacements.forEach { (de, en) -> result = result.replace(de, en, ignoreCase = false) }
    return result
}

internal fun localized(value: String): String = AppLocale.text(value, englishFallback(value))

@Composable
internal fun Text(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: (TextLayoutResult) -> Unit = {},
    style: TextStyle = LocalTextStyle.current,
    "Dieses Profil hat noch keine auswählbare Aktion." to "This profile has no selectable action yet.",
    "Die Reihenfolge bestimmt die Auswahlreihenfolge. Das Overlay zeigt maximal 4, die Benachrichtigung maximal 3 Aktionen. Weitere Aktionen bleiben in der App verfügbar." to "The order here defines selector order. The overlay shows up to 4 actions and notifications up to 3. Additional actions remain available in the app.",
    "Aktion nach oben" to "Move action up",
    "Aktion nach unten" to "Move action down"
) {
    MaterialText(
        text = localized(text),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style
    )
}
